apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-server
  labels:
    deployment: canary-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-server
  template:
    metadata:
      labels:
        app: canary-server
    spec:
      containers:
        - name: canary-server
          image: image
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP