name: Build/Push

on:
  push: 
    branches:
      - yq

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run kustomize
        run: |
          kubectl kustomize ./kubernetes/
